### ISSUE TITLE
Deployed bytecode error

### ISSUE THREAD

**Issue by LayneHaber** [armaniferrante/pure-evm#6]
Trying to use this package to run `view` functions, and running into some strange issues.

When I try to call `execute` with the bytecode retrieved from `eth_getCode` (the runtime/deployed bytecode), I get a rust panic error:
```bash
RuntimeError: unreachable
        at __rust_start_panic (wasm-function[330]:0x3a810)
        at rust_panic (wasm-function[213]:0x39f81)

      313 |
      314 |       // Execute on the raw bytes.
    > 315 |       const output = pure_evm.exec(
          |                               ^
      316 |         Uint8Array.from(Buffer.from(bytecode.replace("0x", ""), "hex")),
      317 |         encodedData,
      318 |       );

      at std::panicking::rust_panic_with_hook::h5e7c2dc110ae79d4 (wasm-function[95]:0x36e5a)
      at std::panicking::begin_panic::h6da1813f9eea9b6a (wasm-function[200]:0x39c59)
      at <pure_evm::pure_ext::PureExt as vm::ext::Ext>::depth::he3b3a85b57bdb8e8 (wasm-function[273]:0x3a540)
      at evm::interpreter::Interpreter<Cost>::exec_instruction::h8137cbc088506585 (wasm-function[1]:0xc988)
      at <evm::interpreter::Interpreter<Cost> as vm::Exec>::exec::h41e00997af783aac (wasm-function[5]:0x1df67)
      at pure_evm::exec::h1eb45dc630e9c525 (wasm-function[10]:0x24982)
          at exec (wasm-function[92]:0x36a29)
      at Object.module.exports.exec (../../node_modules/pure-evm/pure-evm_main.js:38:22)
      at AppInstance.computeStateTransition (src/models/app-instance.ts:315:31)
          at runMicrotasks (<anonymous>)
```

Interestingly enough, when using the init/creation bytecode, the error disappears and the output of the `execute` function once converted to a hex string is the same as the deployed bytecode returned from `eth_getCode`. Any idea on what might be causing these errors?

Here is a code snippet (running in node env, not browser):
```typescript
const appArtifact = require(`@connext/contracts/artifacts/${pureAppName}.json`);
const iface = new Interface(appArtifact.abi);

// applyAction is a view function, using solidity 0.6
const data = iface.encodeFunctionData("applyAction", [
        this.encodedLatestState,
        this.encodeAction(action),
]);
const encodedData = Uint8Array.from(Buffer.from(data.replace("0x", ""), "hex"));

const bytecode = await provider.send("eth_getCode", [this.appDefinition, "latest"]);

// Works IFF using init bytecode, but returns deployed bytecode hex string. Fails otherwise.
const output = pure_evm.exec(
        Uint8Array.from(Buffer.from(bytecode.replace("0x", ""), "hex")),
        encodedData,
);

// Taken from the ttt test
const bytes = defaultAbiCoder.decode(["bytes"], output)[0];
const computedNextState = defaultAbiCoder.decode([this.abiEncodings.stateEncoding], bytes)[0];
```

**Comment by armaniferrante** [comment]
Without looking at your code, it seems the problem is that the `depth()` externality is being called by your code.

I took a quick look at the parity-ethereum/open-ethereum codebase and it looks like it's only called on [contract creation](https://github.com/openethereum/openethereum/blob/master/ethcore/evm/src/interpreter/mod.rs#L602) or [cross contract calls](https://github.com/openethereum/openethereum/blob/master/ethcore/evm/src/interpreter/mod.rs#L685).

So I would guess your bytecode has at least one of those opcodes in it.

**Comment by LayneHaber** [comment]
Sure, [here]() is a simple reproduction. Just install, build, and test and you should see the same failure.

That's interesting. Was chatting with @HeikoFisch about it on our side, and we were thinking it might be due to the usage of `sha256` or `recover` within the `pure or `view` function

**Comment by armaniferrante** [comment]
If I recall correctly, all Ethereum "builtin" functions like `sha256` and `recover` execute as cross contract calls at builtin addresses, which would explain the error you're receiving.

**Comment by LayneHaber** [comment]
Yeah, they would appear as contract calls in the compiled code.

So even though this is accepted as `pure` by the EVM it doesn't look like it will work within this library, bummer! Do you have any plans on supporting these precompile calls in the future?

**Comment by armaniferrante** [comment]
There's currently no plans for feature development on this project, but I filed a new issue to track this feature request. See #7.

**Comment by LayneHaber** [comment]
Awesome, thanks!
